version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=44322
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/temain-tk.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "44322:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  priceissuer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=44332
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/temain-tk.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "44332:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
